### ISSUE TITLE
[Nest] 9676

### ISSUE THREAD

**Issue by iCodeDesigns** [ramymaghraby/einvoice#1]
After running `npm run start` 
getting this error:
`[ExceptionsHandler] ENOENT: no such file or directory, stat 'C:\Users\example\Desktop\code\einvoice-master\backend\dist\client\index.html'`

**Comment by ramymaghraby** [comment]
Thank you for your comment, will fix this in my next push.
But please be noted that this is still a work in progress, i am not done with this project yet, I'm just backing up my code to this repo
